name: Issue - Responder

on:
  issues:
    types: [closed]
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        if: contains(github.event.issue.labels.*.name, 'deployment')
        run: echo Version is ${{ github.event.issue.body }}
