name: Try Log Secrets

on:
  workflow_dispatch:
    inputs: 
      logLevel:
        description: 'Log Level'
        required: true
        default: 'warning'
      tags:
        description: 'Test Scenario tags'
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  log:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      # Runs a single command using the runners shell
      - name: Log the secret
        run: echo ${{ secrets.MY_SECRET }}

